-- MySQL Script generated by MySQL Workbench
-- Sat Sep 19 07:13:18 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema OpticianStore
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `OpticianStore` ;

-- -----------------------------------------------------
-- Schema OpticianStore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OpticianStore` DEFAULT CHARACTER SET utf8 ;
USE `OpticianStore` ;

-- -----------------------------------------------------
-- Table `OpticianStore`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OpticianStore`.`Supplier` (
  `idSupplier` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `street` VARCHAR(60) NOT NULL,
  `number` INT NOT NULL,
  `floor` INT NOT NULL,
  `door` INT NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `postal_code` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `phone` INT NOT NULL,
  `fax` INT NOT NULL,
  `nif` VARCHAR(15) NOT NULL,
  UNIQUE INDEX `idSupplier_UNIQUE` (`idSupplier` ASC) VISIBLE,
  PRIMARY KEY (`idSupplier`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OpticianStore`.`Glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OpticianStore`.`Glasses` (
  `idGlasses` INT NOT NULL,
  `brand` VARCHAR(45) NOT NULL,
  `graduation_left` DECIMAL NOT NULL,
  `graduation_right` DECIMAL NOT NULL,
  `frame` VARCHAR(45) NOT NULL,
  `frame_color` VARCHAR(45) NOT NULL,
  `color_left` VARCHAR(45) NOT NULL,
  `color_right` VARCHAR(45) NOT NULL,
  `price` DECIMAL NOT NULL,
  `Supplier_idSupplier` INT NOT NULL,
  PRIMARY KEY (`idGlasses`),
  UNIQUE INDEX `idGlasses_UNIQUE` (`idGlasses` ASC) VISIBLE,
  INDEX `fk_Glasses_Supplier_idx` (`Supplier_idSupplier` ASC) VISIBLE,
  CONSTRAINT `fk_Glasses_Supplier`
    FOREIGN KEY (`Supplier_idSupplier`)
    REFERENCES `OpticianStore`.`Supplier` (`idSupplier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OpticianStore`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OpticianStore`.`Customer` (
  `idCustomer` INT NOT NULL,
  `name` VARCHAR(60) NOT NULL,
  `postal_address` VARCHAR(45) NOT NULL,
  `phone` INT NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `registration_date` DATE NOT NULL,
  `recommended_by` INT NULL,
  UNIQUE INDEX `idCustomer_UNIQUE` (`idCustomer` ASC) VISIBLE,
  PRIMARY KEY (`idCustomer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OpticianStore`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OpticianStore`.`Employee` (
  `idEmployee` INT NOT NULL,
  `name` VARCHAR(60) NULL,
  UNIQUE INDEX `idEmployee_UNIQUE` (`idEmployee` ASC) VISIBLE,
  PRIMARY KEY (`idEmployee`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OpticianStore`.`Purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OpticianStore`.`Purchase` (
  `idPurchase` INT NOT NULL,
  `Glasses_idGlasses` INT NOT NULL,
  `Customer_idCustomer` INT NOT NULL,
  `Employee_idEmployee` INT NOT NULL,
  UNIQUE INDEX `idPurchase_UNIQUE` (`idPurchase` ASC) VISIBLE,
  PRIMARY KEY (`idPurchase`),
  INDEX `fk_Purchase_Glasses1_idx` (`Glasses_idGlasses` ASC) VISIBLE,
  INDEX `fk_Purchase_Customer1_idx` (`Customer_idCustomer` ASC) VISIBLE,
  INDEX `fk_Purchase_Employee1_idx` (`Employee_idEmployee` ASC) VISIBLE,
  CONSTRAINT `fk_Purchase_Glasses1`
    FOREIGN KEY (`Glasses_idGlasses`)
    REFERENCES `OpticianStore`.`Glasses` (`idGlasses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Purchase_Customer1`
    FOREIGN KEY (`Customer_idCustomer`)
    REFERENCES `OpticianStore`.`Customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Purchase_Employee1`
    FOREIGN KEY (`Employee_idEmployee`)
    REFERENCES `OpticianStore`.`Employee` (`idEmployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
